name: layout
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: any
  logger: any
  # import 'package:logger/logger.dart';
  flutter_svg: ^1.0.1
  floor: any
  flutter_slidable: ^1.2.0


  flutter:
    sdk: flutter
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  floor_generator: any
  build_runner: any

flutter:
  uses-material-design: true
  # assets:
  #  - images/rainier.jpg